### ISSUE TITLE
Nukta position is ambiguous in conjuncts

### ISSUE THREAD

**Issue by dscorbett** [notofonts/kaithi#20]
### Font
NotoSansKaithi-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/kaithi/releases/tag/NotoSansKaithi-v2.004
Date: 2022-09-24

### Font version
Version 2.004

### Issue
A nukta is positioned the same, or almost the same, no matter which element of a conjunct it belongs to, which is confusing.

### Character data
𑂍𑂺𑂹𑂧𑂍𑂹𑂧𑂺
U+1108D KAITHI LETTER KA
U+110BA KAITHI SIGN NUKTA
U+110B9 KAITHI SIGN VIRAMA
U+110A7 KAITHI LETTER MA
U+1108D KAITHI LETTER KA
U+110B9 KAITHI SIGN VIRAMA
U+110A7 KAITHI LETTER MA
U+110BA KAITHI SIGN NUKTA

𑂫𑂹𑂩𑂥𑂹𑂩𑂺
U+110AB KAITHI LETTER VA
U+110B9 KAITHI SIGN VIRAMA
U+110A9 KAITHI LETTER RA
U+110A5 KAITHI LETTER BA
U+110B9 KAITHI SIGN VIRAMA
U+110A9 KAITHI LETTER RA
U+110BA KAITHI SIGN NUKTA

### Screenshot
![𑂍𑂺𑂹𑂧𑂍𑂹𑂧𑂺 𑂫𑂹𑂩𑂥𑂹𑂩𑂺](https://user-images.githubusercontent.com/1124347/192118013-40e5a459-6d9a-4f88-9f9c-5dfd1079ccb8.png)

**Comment by simoncozens** [comment]
Ok. Treating conjuncts as ligatures for the purposes of positioning a nukta which probably shouldn't be there anyway is going to cause a lot of disruption for minimal gain.
