### ISSUE TITLE
Vowel sign -u is misplaced on dotless ya

### ISSUE THREAD

**Issue by dscorbett** [notofonts/kaithi#22]
### Font
NotoSansKaithi-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/kaithi/releases/tag/NotoSansKaithi-v2.005
Date: 2023-10-01

### Font version
Version 2.005

### Issue
When 'ss03' “Dotless ya forms” is enabled, the vowel sign <i>-u</i> is positioned too far left on <i>ya</i>, both alone and in a conjunct, both without and with 'ss01' “Alternate forms”.

### Character data
𑂨𑂳𑂦𑂹𑂨𑂳𑂍𑂹𑂨𑂳
U+110A8 KAITHI LETTER YA
U+110B3 KAITHI VOWEL SIGN U
U+110A6 KAITHI LETTER BHA
U+110B9 KAITHI SIGN VIRAMA
U+110A8 KAITHI LETTER YA
U+110B3 KAITHI VOWEL SIGN U
U+1108D KAITHI LETTER KA
U+110B9 KAITHI SIGN VIRAMA
U+110A8 KAITHI LETTER YA
U+110B3 KAITHI VOWEL SIGN U

### Screenshot
![𑂨𑂳𑂦𑂹𑂨𑂳𑂍𑂹𑂨𑂳](https://github.com/notofonts/kaithi/assets/1124347/d7b3c877-a341-492d-9263-413f39996569)

With 'ss01':
![𑂍𑂹𑂨𑂳](https://github.com/notofonts/kaithi/assets/1124347/a702a769-0b4a-4363-956e-2e38ea4f9b04)

**Comment by simoncozens** [comment]
I've added the missing anchors to make the above cases work. I had a look for other `.alt` glyphs which had Anchor4 but were missing Anchor8, but couldn't see any.
