### ISSUE TITLE
ZWJ repositions virama slightly

### ISSUE THREAD

**Issue by dscorbett** [notofonts/kaithi#28]
### Font
NotoSansKaithi-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/kaithi/releases/tag/NotoSansKaithi-v2.005
Date: 2023-10-01

### Font version
Version 2.005

### Issue
Glyphs that act like half forms but have visible viramas look different from the equivalent sequences of the full forms with separate virama glyphs. For example, <<i>nga</i>, virama, ZWJ> looks similar but not identical to <<i>nga</i>, virama>. The position of the virama is different. Because they represent the same thing, and it is only a quirk of Unicode and OpenType that they are distinguished, they should look the same.

### Character data
𑂑𑂹‍ 𑂓𑂹‍ 𑂕𑂹‍ 𑂗𑂹‍ 𑂘𑂹‍ 𑂙𑂹‍ 𑂚𑂹‍ 𑂛𑂹‍ 𑂜𑂹‍ 𑂠𑂹‍ 𑂩𑂹‍ 𑂪𑂹‍ 𑂯𑂹‍
U+11091 KAITHI LETTER NGA
U+110B9 KAITHI SIGN VIRAMA
U+200D ZERO WIDTH JOINER
U+0020 SPACE
U+11093 KAITHI LETTER CHA
U+110B9 KAITHI SIGN VIRAMA
U+200D ZERO WIDTH JOINER
U+0020 SPACE
U+11095 KAITHI LETTER JHA
U+110B9 KAITHI SIGN VIRAMA
U+200D ZERO WIDTH JOINER
U+0020 SPACE
U+11097 KAITHI LETTER TTA
U+110B9 KAITHI SIGN VIRAMA
U+200D ZERO WIDTH JOINER
U+0020 SPACE
U+11098 KAITHI LETTER TTHA
U+110B9 KAITHI SIGN VIRAMA
U+200D ZERO WIDTH JOINER
U+0020 SPACE
U+11099 KAITHI LETTER DDA
U+110B9 KAITHI SIGN VIRAMA
U+200D ZERO WIDTH JOINER
U+0020 SPACE
U+1109A KAITHI LETTER DDDHA
U+110B9 KAITHI SIGN VIRAMA
U+200D ZERO WIDTH JOINER
U+0020 SPACE
U+1109B KAITHI LETTER DDHA
U+110B9 KAITHI SIGN VIRAMA
U+200D ZERO WIDTH JOINER
U+0020 SPACE
U+1109C KAITHI LETTER RHA
U+110B9 KAITHI SIGN VIRAMA
U+200D ZERO WIDTH JOINER
U+0020 SPACE
U+110A0 KAITHI LETTER DA
U+110B9 KAITHI SIGN VIRAMA
U+200D ZERO WIDTH JOINER
U+0020 SPACE
U+110A9 KAITHI LETTER RA
U+110B9 KAITHI SIGN VIRAMA
U+200D ZERO WIDTH JOINER
U+0020 SPACE
U+110AA KAITHI LETTER LA
U+110B9 KAITHI SIGN VIRAMA
U+200D ZERO WIDTH JOINER
U+0020 SPACE
U+110AF KAITHI LETTER HA
U+110B9 KAITHI SIGN VIRAMA
U+200D ZERO WIDTH JOINER

𑂑𑂹 𑂓𑂹 𑂕𑂹 𑂗𑂹 𑂘𑂹 𑂙𑂹 𑂚𑂹 𑂛𑂹 𑂜𑂹 𑂠𑂹 𑂩𑂹 𑂪𑂹 𑂯𑂹
U+11091 KAITHI LETTER NGA
U+110B9 KAITHI SIGN VIRAMA
U+0020 SPACE
U+11093 KAITHI LETTER CHA
U+110B9 KAITHI SIGN VIRAMA
U+0020 SPACE
U+11095 KAITHI LETTER JHA
U+110B9 KAITHI SIGN VIRAMA
U+0020 SPACE
U+11097 KAITHI LETTER TTA
U+110B9 KAITHI SIGN VIRAMA
U+0020 SPACE
U+11098 KAITHI LETTER TTHA
U+110B9 KAITHI SIGN VIRAMA
U+0020 SPACE
U+11099 KAITHI LETTER DDA
U+110B9 KAITHI SIGN VIRAMA
U+0020 SPACE
U+1109A KAITHI LETTER DDDHA
U+110B9 KAITHI SIGN VIRAMA
U+0020 SPACE
U+1109B KAITHI LETTER DDHA
U+110B9 KAITHI SIGN VIRAMA
U+0020 SPACE
U+1109C KAITHI LETTER RHA
U+110B9 KAITHI SIGN VIRAMA
U+0020 SPACE
U+110A0 KAITHI LETTER DA
U+110B9 KAITHI SIGN VIRAMA
U+0020 SPACE
U+110A9 KAITHI LETTER RA
U+110B9 KAITHI SIGN VIRAMA
U+0020 SPACE
U+110AA KAITHI LETTER LA
U+110B9 KAITHI SIGN VIRAMA
U+0020 SPACE
U+110AF KAITHI LETTER HA
U+110B9 KAITHI SIGN VIRAMA

𑂍𑂹‍ 𑂖𑂹‍ 𑂤𑂹‍ 𑂪𑂹‍
U+1108D KAITHI LETTER KA
U+110B9 KAITHI SIGN VIRAMA
U+200D ZERO WIDTH JOINER
U+0020 SPACE
U+11096 KAITHI LETTER NYA
U+110B9 KAITHI SIGN VIRAMA
U+200D ZERO WIDTH JOINER
U+0020 SPACE
U+110A4 KAITHI LETTER PHA
U+110B9 KAITHI SIGN VIRAMA
U+200D ZERO WIDTH JOINER
U+0020 SPACE
U+110AA KAITHI LETTER LA
U+110B9 KAITHI SIGN VIRAMA
U+200D ZERO WIDTH JOINER

𑂍𑂹 𑂖𑂹 𑂤𑂹 𑂪𑂹
U+1108D KAITHI LETTER KA
U+110B9 KAITHI SIGN VIRAMA
U+0020 SPACE
U+11096 KAITHI LETTER NYA
U+110B9 KAITHI SIGN VIRAMA
U+0020 SPACE
U+110A4 KAITHI LETTER PHA
U+110B9 KAITHI SIGN VIRAMA
U+0020 SPACE
U+110AA KAITHI LETTER LA
U+110B9 KAITHI SIGN VIRAMA

### Screenshots
![𑂑𑂹‍ 𑂓𑂹‍ 𑂕𑂹‍ 𑂗𑂹‍ 𑂘𑂹‍ 𑂙𑂹‍ 𑂚𑂹‍ 𑂛𑂹‍ 𑂜𑂹‍ 𑂠𑂹‍ 𑂩𑂹‍ 𑂪𑂹‍ 𑂯𑂹‍](https://github.com/notofonts/kaithi/assets/1124347/87fb283c-e5e8-41aa-9c82-b6cc101ece1c)
![𑂑𑂹 𑂓𑂹 𑂕𑂹 𑂗𑂹 𑂘𑂹 𑂙𑂹 𑂚𑂹 𑂛𑂹 𑂜𑂹 𑂠𑂹 𑂩𑂹 𑂪𑂹 𑂯𑂹](https://github.com/notofonts/kaithi/assets/1124347/f30dd1cd-f80b-4a69-a175-e54a716e70cd)

With 'ss01':

![𑂍𑂹‍ 𑂖𑂹‍ 𑂤𑂹‍ 𑂪𑂹‍](https://github.com/notofonts/kaithi/assets/1124347/e72a3ea3-0f81-472c-9fc6-e8bf968ed000)
![𑂍𑂹 𑂖𑂹 𑂤𑂹 𑂪𑂹](https://github.com/notofonts/kaithi/assets/1124347/d8171c6e-dcc1-4cbf-8936-4e544a34c6dd)

**Comment by simoncozens** [comment]
This seems to have fixed itself...

```
$ shape variable_ttf/NotoSansKaithi-Regular-VF.ttf "𑂍𑂹 𑂖𑂹 𑂤𑂹 𑂪𑂹 𑂍𑂹‍ 𑂖𑂹‍ 𑂤𑂹‍ 𑂪𑂹‍" --features=+ss01
```
![shape](https://github.com/notofonts/kaithi/assets/106728/81ef9c99-cc9e-43e0-ab10-ff6f0d02fd8d)
